version: '2'
services:
  simpleinventory-app:
    image: simpleinventory
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://simpleinventory-mssql:1433;database=SimpleInventory
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  simpleinventory-mssql:
    extends:
      file: mssql.yml
      service: simpleinventory-mssql
